apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  image: kubespheredev/fluent-bit:v1.7.3
  positionDB:
    emptyDir: {}
  fluentBitConfigName: fluent-bit-config
  tolerations:
    - operator: Exists
