apiVersion: fluentbit.fluent.io/v1alpha2
kind: Filter
metadata:
  name: containerd
  namespace: kubesphere-logging-system
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  match: kube.*
  filters:
  - lua:
      script:
        key: containerd.lua
        name: fluent-bit-containerd-config
      call: containerd
      timeAsTable: true
