apiVersion: fluentbit.fluent.io/v1alpha2
kind: Input
metadata:
  name: kubelet
  namespace: kubesphere-logging-system
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  systemd:
    tag: service.kubelet
    path: /var/log/journal
    db: /fluent-bit/tail/kubelet.db
    dbSync: Normal
    systemdFilter:
      - _SYSTEMD_UNIT=kubelet.service