{{- if .Values.Kubernetes -}}
{{- if .Values.output.fluentd.kafka.enable -}}
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: fluentd-output-kafka
  labels:
    output.fluentd.fluent.io/enabled: "true"
spec:
  outputs:
    - kafka:
        brokers: {{.Values.output.fluentd.kafka.brokers }}
        useEventTime: true
        topicKey: {{.Values.output.fluentd.kafka.topicKey }}
  {{- end }}
  {{- end }}