{{- if .Values.Kubernetes -}}
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterFluentdConfig
metadata:
  name: fluentd-config
  labels:
    config.fluentd.fluent.io/enabled: "true"
spec:
  watchedNamespaces:
  {{- range .Values.flentd.watchedNamespaces }}
  - {{ . }}
  {{- end }}
  clusterOutputSelector:
    matchLabels:
      output.fluentd.fluent.io/enabled: "true"
  {{- end }}
