apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBit
metadata:
  name: fluentbit-sample
  labels:
    app: fluent-bit
spec:
  image: kubesphere/fluent-bit:v1.6.2
  imagePullPolicy: IfNotPresent
  positionDB:
    emptyDir: {}
  fluentBitConfigName: fluentbitconfig-sample
