{{- if .Values.Kubernetes -}}
{{- if .Values.output.kafka.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: Output
metadata:
  name: kafka
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  kafka:
    brokers: {{ .Values.output.kafka.brokers }}
    topics: ks-log
  {{- end }}
  {{- end }}