{{- if .Values.Kubernetes -}}
{{- if .Values.output.forward.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: Output
metadata:
  name: fluentd
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  forward:
    host: {{ .Values.output.forward.host }}
    port: {{ .Values.output.forward.port }}
  {{- end }}
  {{- end }}